max_jobs: 1

image: Visual Studio 2022

cache:
  - '%LocalAppData%\NuGet\v3-cache'

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

install:
  - cmd: dotnet tool install -g Cake.Tool --version 0.38.5

build_script:
  - cmd: dotnet cake --target=Full

test: off

artifacts:
  - path: outputs\*.nupkg
    name: packages
  - path: outputs\*.snupkg
    name: symbols
  - path: outputs\tests\report
    name: report
    type: zip

deploy:
  - provider: Environment
    name: MyGet EMG Public
    on:
      branch: master
  - provider: Environment
    name: NuGet EMG
    on:
      branch: master
      appveyor_repo_tag: true
  - provider: Environment
    name: EMG GPR
    on:
      branch: master
      appveyor_repo_tag: true
